name: Step 3, Upload test reports

# This step triggers after push to the ci.yml file on the ci branch.
# This workflow updates from step 3 to step 4.

# This will run every time we push to the ci.yml file on the ci branch.
# Reference: https://docs.github.com/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - ci
    paths:
      - .github/workflows/ci.yml

# Reference: https://docs.github.com/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent vfile-reporter-json
          npx remark . --use remark-preset-lint-consistent --report vfile-reporter-json 2> remark-lint-report.json

      - name: Upload lint report
        uses: actions/upload-artifact@v4
        with:
          name: remark-lint-report
          path: remark-lint-report.json

